// Константы приложения

export const ROLES = {
  ADMIN: 'ROLE_ADMIN',
  EDITOR: 'ROLE_EDITOR',
  SUBSCRIBER: 'ROLE_SUBSCRIBER',
} as const;

export const ACTION_TYPES = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  REGISTER: 'REGISTER',
  CREATE_NEWS: 'CREATE_NEWS',
  UPDATE_NEWS: 'UPDATE_NEWS',
  DELETE_NEWS: 'DELETE_NEWS',
  SUBSCRIBE_CATEGORY: 'SUBSCRIBE_CATEGORY',
  UNSUBSCRIBE_CATEGORY: 'UNSUBSCRIBE_CATEGORY',
  UPDATE_USER_ROLE: 'UPDATE_USER_ROLE',
} as const;

export const PASSWORD_MIN_LENGTH = 8;
export const USERNAME_MIN_LENGTH = 3;
